=== vdragan1993/xml-project/parliament/api/schema/XML_Proj_schema_act.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified"
    targetNamespace="http://ftn.uns.ac.rs/xml" xmlns:proj="http://ftn.uns.ac.rs/xml">

    <xs:element name="akt">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="1" name="preambula" type="proj:sadrzaj"/>
                <xs:choice maxOccurs="1" minOccurs="1">
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="2" ref="proj:deo"/>
                    </xs:sequence>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="2" ref="proj:glava"/>
                    </xs:sequence>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="2" ref="proj:clan"/>
                    </xs:sequence>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="naslov" type="xs:string" use="required"/>
            <xs:attribute name="drzava" type="xs:string" use="required"/>
            <xs:attribute name="opstina" type="xs:string" use="required"/>
            <xs:attribute name="grad" type="xs:string" use="required"/>
            <xs:attribute name="ustanova_organ" type="xs:string" use="required"/>
            <xs:attribute name="datum_kreiranja" type="xs:date" use="required"/>
            <xs:attribute name="datum_usvajanja" type="xs:date" use="optional"/>
            <xs:attribute name="predlagac" type="xs:string" use="required"/>
            <xs:attribute name="status" type="xs:string" use="required"/>
            <xs:attribute name="kategorija" type="xs:string" use="required"/>
            <xs:attribute name="za" type="xs:int" use="optional"/>
            <xs:attribute name="protiv" type="xs:int" use="optional"/>
            <xs:attribute name="uzdrzani" type="xs:int" use="optional"/>
            <xs:attribute name="br_sluzbenog_glasnika" type="xs:string" use="optional"/>
            <xs:attribute name="datum_pocetka_vazenja" type="xs:date" use="optional"/>
            <xs:attribute name="datum_prestanka_vazenja" type="xs:date" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="deo">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="proj:glava"/>
            </xs:sequence>
            <xs:attribute name="naslov" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="glava">
        <xs:complexType>
            <xs:choice>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="1" ref="proj:clan"/>
                </xs:sequence>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="1" ref="proj:odeljak"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="naslov" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="clan">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="proj:stav"/>
            </xs:sequence>
            <xs:attribute name="rbr" type="xs:string"/>
            <xs:attribute name="naslov" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="odeljak">
        <xs:complexType>
            <xs:choice>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="1" ref="proj:pododeljak"/>
                </xs:sequence>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="1" ref="proj:clan"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="naslov" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="stav">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:choice maxOccurs="unbounded" minOccurs="1">
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="proj:tacka"/>
                    <xs:element name="tekst" type="proj:sadrzaj"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pododeljak">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="proj:clan"/>
            </xs:sequence>
            <xs:attribute name="naslov" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="tacka">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:choice maxOccurs="unbounded" minOccurs="1">
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="proj:podtacka"/>
                    <xs:element name="tekst" type="proj:sadrzaj"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="podtacka">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:choice maxOccurs="unbounded" minOccurs="1">
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="proj:alineja"/>
                    <xs:element name="tekst" type="proj:sadrzaj"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="alineja" type="proj:sadrzaj"/>
    <xs:complexType mixed="true" name="sadrzaj">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="blok">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="uri" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== vdragan1993/xml-project/parliament/api/download/Pravilnik_javne_nabavke.xml
<?xml version="1.0"?>
<proj:akt xsi:schemaLocation="http://ftn.uns.ac.rs/xml file:/D:/Fakultet/4.godina/XWS/XML/XML_Proj_schema_act.xsd" naslov="Pravilnik o bližem uređivanju postupka javne nabavke za Skupštinu Grada Novog Sada, Gradsku izbornu komisiju i Službu Skupštine Grada Novog Sada" drzava="Srbija" opstina="Novi Sad" grad="Novi Sad" ustanova_organ="Skupština Grada Novog Sada" datum_kreiranja="2012-05-04" datum_usvajanja="2012-06-05" predlagac="Petar Petrović" status="usvojen" kategorija="pravilnik" za="45" protiv="15" uzdrzani="5" br_sluzbenog_glasnika="124/12" datum_pocetka_vazenja="2006-08-07" datum_prestanka_vazenja="2020-05-05" xmlns:proj="http://ftn.uns.ac.rs/xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <preambula>
        <blok>Na osnovu člana 22. stav 1. Zakona o javnim nabavkama („Službeni glasnik RS”, broj 124/12, 14/15 i 68/15), a u skladu sa Pravilnikom o sadržini akta kojim se bliže uređuje postupak javne nabavke unutar naručioca („Službeni glasnik RS”, broj 106/13) sekretar Skupština Grada Novog Sada, donosi</blok>
    </preambula>
        <proj:glava naslov="Predmet uređivanja">
            <proj:clan rbr="1">
                <proj:stav>
                    <tekst>
                        <blok>
                            Ovim pravilnikom bliže se uređuje procedura planiranja nabavki, 
                            sprovođenje postupaka javnih nabavki i izvršenje ugovora o javnoj nabavci 
                            za Skupštineu Grada Novog Sada, Gradsku izbornu komisiju i Službu Skupštine 
                            Grada Novog Sada ( u daljem tekstu: naručioci).

                            Pravilnikom se uređuju učesnici, odgovornosti,
                            način obavljanja poslova javnih nabavki u skladu sa zakonom kojim se uređuju 
                            javne nabavke (u daljem tekstu: Zakon), a naročito se uređuje način 
                            planiranja nabavki (kriterijumi, pravila i način određivanja predmeta 
                            javne nabavke i procenjene vrednosti, način ispitivanja i istraživanja tržišta),
                            odgovornost za planiranje, ciljevi postupka javne nabavke, način izvršavanja
                            obaveza iz postupka, način obezbeđivanja konkurencije, sprovođenje i kontrola
                            javnih nabavki, način praćenja izvršenja ugovora o javnoj nabavci.

                            Pravilnik se primenjuje i na nabavke dobara ili usluga ili ustupanje 
                            izvođenja radova, na koje se ne primenjuju propisi kojima se uređuju javne
                            nabavke.
                        </blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
        </proj:glava>
        <proj:glava naslov="Osnovne odredbe">
            <proj:clan rbr="2" naslov="Primena">
                <proj:stav>
                    <tekst>
                        <blok>
                            Ovaj pravilnik je namenjen svim organizacionim jedinicama Službe Skupštine 
                            Grada Novog Sada (u daljem tekstu: Organizacione jedinice), koja obavlja 
                            stručne i druge poslove za Skupštinu Grada Novog Sada i Gradsku izbornu 
                            komisiju i koje su, u skladu sa važećom regulativom i unutrašnjim opštim 
                            aktima, uključeni u planiranje nabavki, sprovođenje postupaka javnih nabavki,
                            izvršenje ugovora i kontrolu javnih nabavki.

                            Za Skupštinu Grada Novog Sada, Gradsku izbornu komisiju i Službu Skupštine
                            Grada Novog Sada, kao Naručioca, postupke javnih nabavki sprovodi Služba za
                            zajedničke poslove Grada Novog Sada – Sektor za javne nabavke
                            (u daljem tekstu: Sektor), na osnovu člana 27. stav 7. Odluke o Gradskim
                            upravama Grada Novog Sada („Službeni list Grada Novog Sada“, br. 52/08, 55/09,
                            11/10, 39/10, 60/10 i 69/13).
                            U Sektoru se obavljaju poslovi sprovođenja postupaka javnih nabavki za koja 
                            su sredstva obezbeđena u budžetu, odnosno u finansijskom planu Skupštine
                            Grada Grada Novog Sada i Službe za zajedničke poslove Grada Novog Sada.

                            Sektorom rukovodi šef Sektora koji ima pomoćnike.
                        </blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
            <proj:clan rbr="3" naslov="Pojmovi">
                <proj:stav>
                    <tekst>
                        <blok>
                            Javnom nabavkom smatra se pribavljanje dobara ili usluga ili 
                            ustupanje izvođenja radova, u skladu sa propisima kojima se uređuju
                            javne nabavke i ovim pravilnikom.

                            Nabavka koja je izuzeta od primene Zakona je nabavka predmeta nabavke 
                            potrebanih za obavljanje delatnosti Organizacionih jedinica, a na koju
                            se na osnovu zakonske regulative ne primenjuju odredbe Zakona.

                            Poslovi javnih nabavki su planiranje javne nabavke; sprovođenje postupka
                            javne nabavke uključujući ali ne ograničavajući se na učešće u komisiji 
                            za javnu nabavku; izrada konkursne dokumentacije; izrada akata u postupku 
                            javne nabavke; izrada ugovora o javnoj nabavci; praćenje izvršenja javne 
                            nabavke; svi drugi poslovi koji su povezani sa postupkom javne nabavke.

                            Ponuđač je lice koje u postupku javne nabavke ponudi dobra, pružanje 
                            usluga ili izvođenje radova.

                            Ugovor o javnoj nabavci je teretni ugovor zaključen u pisanoj ili elektronskoj
                            formi između jednog ili više ponuđača i jednog ili više naručilaca, 
                            koji za predmet ima nabavku dobara, pružanje usluga ili izvođenje radova.

                            Ugovor o javnoj nabavci (u daljem tekstu: ugovor) se zaključuje nakon
                            sprovedenog otvorenog i restriktivnog postupka, a može da se zaključi i
                            nakon sprovedenog kvalifikacionog postupka, pregovaračkog postupka sa
                            objavljivanjem poziva za podnošenje ponuda, pregovaračkog postupka bez 
                            objavljivanja poziva za podnošenje ponuda, konkurentnog dijaloga,
                            konkursa za nacrte i postupka javne nabavke male vrednosti, ako su za to 
                            ispunjeni Zakonom propisani uslovi. Postupak javne nabavke sprovodi se u
                            skladu s načelima Zakona.
                        </blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
        </proj:glava>
        <proj:glava naslov="Način planiranja nabavki">
            <proj:clan rbr="5">
                <proj:stav>
                    <tekst>
                        <blok>
                            Pravilnikom se uređuju ovlašćenja u planiranju nabavki, postupak planiranja nabavki,
                            rokovi izrade i donošenja plana javnih nabavki, 
                            kao i druga pitanja od značaja na način planiranja nabavki.
                        </blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
            <proj:clan rbr="6">
                <proj:stav>
                    <tekst>
                        <blok>
                            Godišnji plan nabavki sadrži obavezne elemente određene Zakonom i 
                            podzakonskim aktom i mora biti usaglašen sa budžetom Republike Srbije, 
                            teritorijalne autonomije, lokalne samouprave ili finansijskim planom naručioca.
                        
                            Godišnji plan nabavki donosi nadležni organ naručioca poštujući pravila o 
                            njegovom sačinjavanju i dostavljanju koja su propisana Zakonom i podzakonskim aktom.
                        </blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
        </proj:glava>
</proj:akt>

=== vdragan1993/xml-project/parliament/api/download/Odluka.xml
<?xml version="1.0"?>
<proj:akt xsi:schemaLocation="http://ftn.uns.ac.rs/xml file:/D:/Fakultet/4.godina/XWS/XML/XML_Proj_schema_act.xsd" naslov="Odluka o određivanju zona na teritoriji Grada Novog Sada sa koeficijentima za nepokretnosti u zonama za potrebe utvrđivanja poreza na imovinu" drzava="Srbija" opstina="Novi Sad" grad="Novi Sad" ustanova_organ="Skupština Grada Novog Sada" datum_kreiranja="2013-10-23" predlagac="marko" status="u proceduri" kategorija="Odluka" xmlns:proj="http://ftn.uns.ac.rs/xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <preambula>
        <blok>
            Na osnovu člana 6. stav 3, 4, 5, 6. i 7a. Zakona o porezima na imovinu („ Službeni
            glasnik Republike Srbije“,  broj 26/01,	„ Službeni list SRJ“	broj 42/02 –  Odluka US i
            „ Službeni glasnik Republike Srbije“,	br. 80/02, 80/02 –  dr.	Zakon 135/04, 61/07, 5/09,
            101/10, 24/11, 78/11, 57/12, - Odluka US i 47/13), člana 107. stav 1. Statuta Grada Novog Sada
            – prečišćen tekst („ Službeni list Grada Novog Sada“, broj 43/08), Skupština Grada Novog Sada na XXIII sednici 25. oktobra 2013. godine donosi
        </blok>
    </preambula>
            <proj:clan rbr="1">
                <proj:stav>
                    <tekst>
                        <blok>
                            Ovom odlukom određuju se zone na teritoriji Grada Novog Sada sa naznakom 
                            zone koja se smatra najopremljenijom i utvrđuju koeficijenti za svaku zonu
                            za potrebe utvrđivanja poreza na imovinu.
                        </blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
            <proj:clan rbr="2">
                <proj:stav>
                    <tekst>
                        <blok>U zavisnosti od komunalne opremljenosti, opremljenosti javnim objektima i
                    saobraćajne povezanosti sa centralnim delovima jedinice lokalne samouprave, odnosno
                    radnim zonama i drugim sadržajima u naselju, određuje se pet zona na teritoriji Grada
                    Novog Sada.</blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
            <proj:clan rbr="3">
                <proj:stav>
                    <tekst>
                        <blok>
                            Zone iz člana 2. ove odluke i koeficijenti po zonama su:
                            
                            1. Prva zona – najopremljenija zona obuhvata područja mesnih zajednica:
                            „ Žitni trg“, „ Stari grad“, „ Prva vojvođanska brigada“, „ Sonja Marinković“,
                            „ Liman“, „ Boško Buha“, „ Liman III“, „ Ostrvo“, „ Ivo Andrić“, „ Vera Pavlović“,
                            „7. juli“, „ Narodni heroji“, „ Omladinski pokret“, „ Sava Kovačević“ i „ Dunav“.
                            Koeficijent za nepokretnosti u prvoj zoni – najopremljenijoj zoni – 1,00.

                            2. Druga zona obuhvata područja mesnih zajednica: „ Gavrilo Princip“, 
                            „ Bistrica“, „ Detelinara“, „ Jugovićevo“, „ Radnički“, „ Podbara“, „ Salajka“,
                            „ Petrovaradin“, „ Sremska Kamenica“	i „ Ribnjak“.		
                            Koeficijent za nepokretnosti u drugoj zoni – 0,80.

                            3.	Treća	zona	obuhvata područja	mesnih zajednica:  „ Slana bara“,  „ Klisa“,
                            „ Vidovdansko naselje“,	„ Kać“,  „ Južni Telep“,  „ Bratstvo-Telep“,  „ Nikola Tesla-Telep“,
                            „ Adice“, „	Futog“,	„ Veternik“  i „ Sajlovo“	deo područja koje pripada Mesnoj zajendici
                            „ Jugovićevo“.	
                            Koeficijent za nepokretnosti u trećoj zoni – 0,70.	

                            4.  Četvrta	zona	obuhvata područja	mesnih zajednica:  „ Šangaj“,	„ Rumenka“,
                            „ Stepanovićevo“, „	Čenej“,	„ Pejićevi salaši –	Nemanovci“  i „ Alibegovac“,	„ Artiljevo“,
                            „	Popovica“, „ Puckaroš“, „ Vezirac“, „ Zanoš“  deo područja koje pripada Mesnoj zajednici
                            „	Sremska Kamenica“.  
                            Koeficijent za nepokretnosti u četvrtoj zoni – 0,60.

                            5. Peta zona obuhvata područja mesnih zajednica: „ Bukovac“, „ Ledinci“, „ Stari Ledinci“, „ Begeč“, „ Budisava“, „ Kisač“ i „ Kovilj“.
                            Koeficijent za nepokretnosti u petoj zoni – 0,40
                        </blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
            <proj:clan rbr="4">
                <proj:stav>
                    <tekst>
                        <blok>
                            Ova odluka stupa na snagu narednog dana od dana objavljivanja u „ Službenom listu Grada Novog Sada“,
                            a primenjivaće se na utvrđivanje poreza na imovinu za 2014. godinu.
                        </blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
</proj:akt>

=== vdragan1993/xml-project/parliament/api/download/Poslovnik.xml
<?xml version="1.0"?>
<proj:akt xsi:schemaLocation="http://ftn.uns.ac.rs/xml file:/C:/Users/MarkoIvetic/Desktop/xml/XML_Proj_schema_act.xsd" naslov="POSLOVNIK SKUPŠTINE GRADA NOVOG SADA" drzava="Srbija" opstina="Novi Sad" grad="Novi Sad" ustanova_organ="Skupština grada Novog Sada" datum_kreiranja="2006-05-04" datum_usvajanja="2006-05-04" predlagac="Petar Petrovic" status="usvojen" kategorija="Poslovnik" za="50" protiv="10" uzdrzani="5" br_sluzbenog_glasnika="12/2010" datum_pocetka_vazenja="2006-05-04" datum_prestanka_vazenja="2006-05-04" xmlns:proj="http://ftn.uns.ac.rs/xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <preambula>
        <blok>Na osnovu člana 24. tačka 1. Statuta Grada Novog Sada - prečišćen tekst 
            (“Službeni list Grada Novog Sada”, broj 43/2008), Skupština Grada Novog Sada na XXIV sednici 
            26. marta 2010. godine, donela je</blok>
    </preambula>
    <proj:glava naslov="Opšte odredbe">
      
            <proj:clan rbr="1" naslov="">
                <proj:stav>
                    <tekst>
                        <blok>Ovim poslovnikom uređuju se organizacija i rad Skupštine Grada Novog Sada 
                            (u daljem tekstu: Skupš-tina) i ostvarivanje prava i dužnosti odbornika, kao i 
                            druga pitanja od značaja za rad Skupštine.
                            
                            Ako neko pitanje u vezi sa organizacijom i radom Skupštine nije uređeno ovim poslovnikom, 
                            Skupština to pitanje uređuje posebnim aktom.</blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
            <proj:clan rbr="2" naslov="">
                <proj:stav>
                    <tekst>
                        <blok>Sve imenice koje se u ovom poslovniku koriste u muškom rodu, istovremeno obuhvataju i imenice u žen-skom rodu.
                            
                            Imenice koje označavaju službene pozicije, polo-žaje i funkcije u Gradu, koriste se u obliku koji izra-žava pol lica koje je njihov nosilac.</blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
        
    </proj:glava>
    <proj:glava naslov="Konstitutivna sednica skupštine">
        
            <proj:clan rbr="3" naslov="Sazivanje konstitutavine sednice">
                <proj:stav>
                    <tekst>
                        <blok>Konstitutivnu sednicu Skupštine saziva predsed-nik Skupštine iz prethodnog saziva, u roku od 15 dana od dana objavljivanja rezultata izbora.
                        Do izbora predsednika Skupštine, konstitutivnu sednicu Skupštine otvara i njome predsedava najsta-riji prisutan odbornik (predsedavajući) koji je ovla-šćen i da sazove konstitutivnu sednicu ako to u zakons-kom roku ne učini predsednik Skupštine iz prethodnog saziva.</blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
            <proj:clan rbr="4" naslov="Potvrđivanje madata">
                <proj:stav>
                    <tekst>
                        <blok>Odbornici stiču prava i dužnosti odbornika Skupštine danom potvrđivanja mandata.
                        Potvrđivanje mandata odbornika vrši se na osnovu uverenja o izboru odbornika i izveštaja Verifikaci-onog odbora (u daljem tekstu: Odbor). Danom potvrđi-vanja mandata većine odbornika prestaje mandat od-bornika prethodnog saziva Skupštine.</blok>
                    </tekst>
                </proj:stav>
            </proj:clan>
        
    </proj:glava>
</proj:akt>
